### ISSUE TITLE
Handy?

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-07#7]
Hi, ich hab euch heute testiert....ich weiß, das ist eine echt blöde Frage, aber...hat einer von euch zufällig mein Handy mitgenommen? Ich hab's ja nach dem Alarm hinter mir abgelgt, da lag es aber 2 Stunden später nicht mehr.... Wäre dankbar für eine schnelle Antwort. VG

**Comment by HannahBuechner** [comment]
Hey,
Nein tut mir leid, hab zwar mitbekommen, dass du es hinter dich gelegt hast
aber hab am Ende als wir rausgegangen sind nicht mehr darauf geachtet .
Denke auch nicht dass es eine meiner gruppenmitglieder mitgenommen hat, da
wir zusammen aus dem Raum gegangen sind.
Am 11.06.2015 16:21 schrieb "KaroBee" <notifications@github.com>:

**Comment by KaroBee** [comment]
danke
